drop table if exists public.instruments;

create table public.companies (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null,
  industry text not null,
  company_size text,
  website text,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table public.jobs (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete restrict,
  title text not null,
  location text not null,
  distance_miles integer not null check (distance_miles >= 0),
  work_arrangement text not null check (
    work_arrangement in ('onsite', 'hybrid', 'remote')
  ),
  pay_min integer not null check (pay_min >= 0),
  pay_max integer not null check (pay_max >= pay_min),
  job_type text not null check (
    job_type in ('full-time', 'part-time', 'contract', 'internship', 'temporary')
  ),
  experience_level text not null check (
    experience_level in ('entry', 'mid', 'senior', 'executive')
  ),
  date_posted date not null,
  summary text not null,
  description text not null,
  responsibilities text[] not null default '{}',
  qualifications text[] not null default '{}',
  benefits text[] not null default '{}',
  schedule text,
  travel text,
  clearance text,
  visa_note text,
  other_details text[] not null default '{}',
  tags text[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index jobs_active_date_posted_idx
on public.jobs (active, date_posted desc);

create index jobs_company_id_idx
on public.jobs (company_id);

create index jobs_classification_idx
on public.jobs (work_arrangement, job_type, experience_level);

create index jobs_tags_idx
on public.jobs using gin (tags);

grant usage on schema public to anon, authenticated;
revoke all on table public.companies, public.jobs from anon, authenticated;
grant select on table public.companies, public.jobs to anon, authenticated;

alter table public.companies enable row level security;
alter table public.jobs enable row level security;

create policy "Public companies are readable"
on public.companies
for select
to anon, authenticated
using (true);

create policy "Active jobs are publicly readable"
on public.jobs
for select
to anon, authenticated
using (active);
