create table public.instruments (
  id bigint generated by default as identity primary key,
  name text not null,
  section text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

grant usage on schema public to anon, authenticated;
grant select on table public.instruments to anon, authenticated;

alter table public.instruments enable row level security;

create policy "Public instruments are readable"
on public.instruments
for select
to anon, authenticated
using (true);
